# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
