# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
